version: '3.8'

services:
  backend:
    container_name: lde.qualificationWorkForUniversity.api
    build:
      context: .
      dockerfile: QualificationWorkForUniversity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionString=Server=db;Database=master;User=sa;Password=S3cur3P@ssW0rd!;
      - Authorization__Authority=http://www.mi-pizza.ua:5001
      - PathBase=http://www.mi-pizza.ua:5000
    depends_on:
      - db
    ports:
      - 5000:5000
  web.react:
    container_name: lde.web.react
    build: 
      context: ./Web/diploma-react
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  identityserver:
    container_name: lde.identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - ConnectionString=Server=db;Database=master;User=sa;Password=S3cur3P@ssW0rd!;
    ports:
      - 5001:5001
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
       SA_PASSWORD: "S3cur3P@ssW0rd!"
       ACCEPT_EULA: "Y"

networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1